export const mockVideos = [
    {
        id: "1",
        emoji: "🚀",
        gradientFrom: "#FF3B3B",
        gradientTo: "#FF6B35",
        title: "How I Gained 10k Subs in 30 Days",
        sentimentScore: 92,
        commentCount: 1245,
        goodPoints: ["High energy", "Great thumbnail", "Actionable advice"],
        improvPoints: ["Audio slightly echoes", "Intro is too long"],
        flagPoints: ["Some viewers confused by step 3"],
        questions: [
            "Can you make a part 2 on the gear you used?",
            "How did you stay consistent?",
            "Does this work for gaming channels?",
        ],
        nextVideoIdea: "10 Viral Title Strategies Explained",
    },
    {
        id: "2",
        emoji: "💻",
        gradientFrom: "#3B82F6",
        gradientTo: "#2DD4BF",
        title: "Next.js 14 Complete Build Guide",
        sentimentScore: 88,
        commentCount: 890,
        goodPoints: ["Clear explanations", "Good pacing"],
        improvPoints: ["Need more advanced examples", "Background music too loud at 5:00"],
        flagPoints: ["Link in description is broken"],
        questions: [
            "Why use Next over Vite?",
            "How to deploy this to Vercel?",
            "Can we get a TypeScript specific tutorial?",
        ],
        nextVideoIdea: "Next.js App Router Advanced Patterns",
    },
    {
        id: "3",
        emoji: "📸",
        gradientFrom: "#8B5CF6",
        gradientTo: "#EC4899",
        title: "Top 5 Cameras for Beginners 2024",
        sentimentScore: 78,
        commentCount: 3042,
        goodPoints: ["Honest reviews", "Great comparison table"],
        improvPoints: ["Didn't cover cheap lenses", "Lighting was a bit dark"],
        flagPoints: ["Sponsor read was annoying"],
        questions: [
            "What about the Sony ZV-E10?",
            "Best microphone for these?",
        ],
        nextVideoIdea: "Best Budget Audio Gear for YouTubers",
    },
    {
        id: "4",
        emoji: "🎨",
        gradientFrom: "#F59E0B",
        gradientTo: "#EF4444",
        title: "Design Principles Every Dev Should Know",
        sentimentScore: 96,
        commentCount: 512,
        goodPoints: ["Visual examples were stunning", "Short and sweet"],
        improvPoints: ["Could use more code examples"],
        flagPoints: [],
        questions: [
            "Which tool do you use for mockups?",
            "How to handle color contrast for accessibility?",
        ],
        nextVideoIdea: "Tailwind CSS Tips & Tricks for Developers",
    },
    {
        id: "5",
        emoji: "💰",
        gradientFrom: "#10B981",
        gradientTo: "#3B82F6",
        title: "Passive Income Ideas for Creatives",
        sentimentScore: 82,
        commentCount: 2100,
        goodPoints: ["Realistic expectations", "Diverse options"],
        improvPoints: ["Overused stock footage", "Too focused on digital products"],
        flagPoints: ["Sounded a bit scripted"],
        questions: [
            "How to set up Gumroad?",
            "What about taxes?",
        ],
        nextVideoIdea: "Step-by-step Gumroad Store Setup",
    },
    {
        id: "6",
        emoji: "🤖",
        gradientFrom: "#6366F1",
        gradientTo: "#A855F7",
        title: "Building an AI SaaS in 48 Hours",
        sentimentScore: 95,
        commentCount: 980,
        goodPoints: ["Inspiring", "Fast paced", "Showed real code"],
        improvPoints: ["Skipped database setup part"],
        flagPoints: ["API key exposed at 14:22!"],
        questions: [
            "How to scale this?",
            "What database did you use?",
        ],
        nextVideoIdea: "Scaling AI Apps: Database & Auth Setup",
    }
];
